---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д. # необходимо уточнить требование: в товарах отсутствует характеристики цвета, размера, и т.д.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы. # стоит разделить требование на 2, т.к относится к разным областям разработки сайта
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию. # имеет ли смысл в данном требовании, если есть требование адаптивности? (Сайт должен быть доступен на различных устройствах)
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика. # необходимо уточнить требование: большое кол-во трафика - это сколько?
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - При оформлении заказа должно быть поле E-mail для связи с пользователем и подтверждения заказа.
  - Пользователь должен иметь возможность сортировать товары по популярности, по размеру скидки, по возрастанию цены, по убыванию цены.
  - Возможность выбора страницы по Пагинации в формате 1, 2, 3, 4.
